export const internships = [
  {
    id:'001',
    title: 'Desarrollador Web Junior',
    logo: '',
    place: 'Ciudad X, País Y',
    companyDescription: 'Empresa Z es una reconocida empresa de desarrollo web con enfoque en proyectos innovadores.',
    jobDescription: 'Trabaja en equipo para desarrollar aplicaciones web modernas. Aprende y aplica nuevas tecnologías.',
    qualifications: 'Estudiante de informática o campos relacionados. Conocimientos básicos de HTML, CSS y JavaScript.',
    additionalInformation: 'Ofrecemos un ambiente de trabajo colaborativo y oportunidades de aprendizaje continuo.',
    possibleArrivalDates: 'Verano 2023',
    requiredDocumentation: 'Currículum, carta de presentación y transcripciones académicas.',
  },
  {
    id:'002',
    title: 'Diseñador Gráfico en Prácticas',
    logo: '',
    place: 'Ciudad A, País B',
    companyDescription: 'Diseños Creativos es una agencia de diseño que trabaja en proyectos emocionantes.',
    jobDescription: 'Colabora en la creación de gráficos, logotipos y materiales de marketing. Participa en reuniones creativas.',
    qualifications: 'Estudiante de diseño gráfico. Conocimientos de Adobe Creative Suite.',
    additionalInformation: 'Buscamos a alguien apasionado por el diseño y la creatividad.',
    possibleArrivalDates: 'Otoño 2023',
    requiredDocumentation: 'Portafolio, currículum y carta de recomendación.',
  },
  {
    id:'003',
    title: 'Analista de Datos en Formación',
    logo: '',
    place: 'Ciudad B, País C',
    companyDescription: 'Analítica Avanzada es una empresa líder en análisis de datos y consultoría.',
    jobDescription: 'Trabaja en proyectos de análisis de datos. Aprende a utilizar herramientas de análisis y presentación de datos.',
    qualifications: 'Estudiante de estadística, matemáticas o campos relacionados. Conocimientos básicos de estadísticas.',
    additionalInformation: 'Ofrecemos formación y desarrollo profesional en el campo del análisis de datos.',
    possibleArrivalDates: 'Invierno 2023',
    requiredDocumentation: 'Currículum, transcripciones académicas y muestra de habilidades analíticas.',
  },
];
