export const internships = [
  {
    id:'001',
    title: 'CERN Summer Student Programme 2024 (Member and Non-Member State)',
    logo: '/interships/cern.jpg',
    company:'CERN',
    companyDescription: 'At CERN, the European Organization for Nuclear Research, physicists and engineers are probing the fundamental structure of the universe. Using the worlds largest and most complex scientific instruments, they study the basic constituents of matter - fundamental particles that are made to collide together at close to the speed of light. The process gives physicists clues about how particles interact, and provides insights into the fundamental laws of nature. Find out more on home.cern.',
    linkOfficial:'https://www.smartrecruiters.com/CERN/743999941597816-cern-summer-student-programme-2024-member-and-non-member-state-',
    jobDescription: ['Job Description','Take part in CERN’s Summer Student Programme! Over a period of 8 to 13 weeks, you will work on an advanced technical project in an experimental or engineering team. During this unique and exciting time, you can attend a series of lectures specially prepared for you where experts and scientists from around the world share their knowledge about a wide range of topics in the fields of theoretical and experimental particle physics, engineering and computing. Visits to the CERN facilities, as well as discussion sessions and workshops are also key features of the programme. Find out more on the Summer Student information page. A short report on your work and project at CERN will be expected at the end of your stay.'],
    qualifications: ['Qualifications','In order to qualify for a place on the programme you will need to meet the following requirements: You are a Bachelor or Master student (not PhD) in Physics, Engineering, Computer Science or Mathematics and should have completed, by the European Summer 2024, at least 6 semesters of full-time studies in the field, at university level. You will remain registered as a student during your stay at CERN. If you expect to graduate during European summer 2024 (as of May), you are also eligible to apply. You have not worked at CERN before with any other status (Technical Student, Trainee, User or other status) for more than 3 months and you have not been previously a Summer Student at CERN. You have a good knowledge of English; knowledge of French would be an advantage. Candidates of all nationalities are welcome to apply for this Summer Student Programme.']  
  },  {
    id:'002',
    title: 'All UN application websites and Paid Internships',
    logo: '/interships/UNCareers_Logo_EN.PNG',
    company:'UN Careers',
    companyDescription: 'The United Nations promotes international cooperation by harnessing the collective strength of all its Member States to uphold peace and security while advancing the economic and social well-being of all people. Its mission is to ensure the protection of human rights and fundamental freedoms for everyone, irrespective of race, gender, language, or religion. This website focuses on career opportunities within the UN Secretariat, the primary organization in the UN family of Organizations. Our workforce encompasses a diverse array of positions, ranging from internships to senior leadership appointments, covering roles such as archivists, engineers, interpreters, and scientists. Opportunities exist both within office settings and in direct engagement with beneficiaries in local environments. With a presence in hundreds of locations worldwide, there are prospects to switch jobs, departments, and relocate to new places.',
    linkOfficial:'https://careers.un.org/home?language=en',
    first_step:["First step","Create an inspira account: https://inspira.un.org"],
    video:["Video of application","https://inspira-apps.un.org/inspira/videos/external/New_Dashboard-External.mp4"],
    search_map:["Search by map","https://careers.un.org/search-by-map?language=en"],
    search_expertise:["Search my expertise","https://careers.un.org/area-of-expertise?language=en"]
  },
  {
    id:'003',
    title: 'UN Funds and Programmes',
    logo: '/interships/undp-logo-blue.svg',
    company:'United Nations Development Programme',
    companyDescription: 'UNDP works in about 170 countries and territories, helping to eradicate poverty, reduce inequalities and exclusion, and build resilience so countries can sustain progress. As the UN’s development agency, UNDP plays a critical role in helping countries achieve the Sustainable Development Goals. The Sustainable Development Goals (SDGs), otherwise known as the Global Goals, are a universal call to action to end poverty, protect the planet and ensure that all people enjoy peace and prosperity',
    linkOfficial:'https://www.undp.org/',
    vacancies:["Current Vacancies","https://jobs.undp.org/cj_view_jobs.cfm"],
  },
  {
    id:'004',
    title: 'UN Funds and Programmes',
    logo: '/interships/UNVolunteers.PNG',
    company:'United Nations Volunteers',
    companyDescription: 'The United Nations Volunteers (UNV) programme is a United Nations organization that contributes to peace and development through volunteerism worldwide. Volunteerism is a powerful means of engaging people in tackling development challenges, and it can transform the pace and nature of development. Volunteerism benefits both society at large and the individual volunteer by strengthening trust, solidarity and reciprocity among citizens, and by purposefully creating opportunities for participation.',
    linkOfficial:'https://www.unv.org/',
    vacancies:["Current Vacancies","https://app.unv.org/"],
  },
  {
    id:'005',
    title: 'UN Funds and Programmes',
    logo: '/interships/UNCDF.jpg',
    company:'United Nations Capital Development Fund (UNCDF)',
    companyDescription: 'The UN Capital Development Fund makes public and private finance work for the poor in the world’s 46 least developed countries (LDCs). With its unique capital mandate and innovative financing capabilities, UNCDF offers a diverse, innovative and impactful portfolio to tackle climate change, build climate resilience and preserve biodiversity.',
    linkOfficial:'https://www.uncdf.org/',
    vacancies:["Current Vacancies","https://www.uncdf.org/employment"],
  },
  {
    id:'006',
    title: 'UN Funds and Programmes',
    logo: '/interships/unfpa.png',
    company:'United Nations Population Fund (UNFPA)',
    companyDescription: 'UNFPA is the United Nations sexual and reproductive health agency. Our mission is to deliver a world where every pregnancy is wanted, every childbirth is safe and every young person’s potential is fulfilled. We promote gender equality and empower women, girls and young people to take control of their bodies and their futures. We work with partners in more than 150 countries to provide access to a wide range of sexual and reproductive health services. Our goal is ending unmet need for family planning, preventable maternal death, and gender-based violence and harmful practices including child marriage and female genital mutilation by 2030.',
    linkOfficial:'https://www.unfpa.org/',
    vacancies:["Current Vacancies","https://www.unfpa.org/jobs"],
  },
  {
    id:'007',
    title: 'UN Funds and Programmes',
    logo: '/interships/unhabitat.png',
    company:'United Nations Habitat (UN-Habitat)',
    companyDescription: 'The United Nations Human Settlements Programme (UN-Habitat) is mandated by the UN General Assembly to promote socially and environmentally sustainable towns and cities. UN-Habitat is the focal point for all urbanization and human settlement matters within the UN system. UN-Habitat works with partners to build inclusive, safe, resilient and sustainable cities and communities. UN-Habitat promotes urbanization as a positive transformative force for people and communities, reducing inequality, discrimination and poverty',
    linkOfficial:'https://unhabitat.org/',
    vacancies:["Current Vacancies","https://unhabitat.org/join-us"],
  },
  {
    id:'008',
    title: 'UN Funds and Programmes',
    logo: '/interships/unicef.png',
    company:'United Nations International Children’s Emergency Fund (UNICEF)',
    companyDescription: 'UNICEF works in the world’s toughest places to reach the most disadvantaged children and adolescents – and to protect the rights of every child, everywhere. Across more than 190 countries and territories, we do whatever it takes to help children survive, thrive and fulfill their potential, from early childhood through adolescence. The world’s largest provider of vaccines, we support child health and nutrition, safe water and sanitation, quality education and skill building, HIV prevention and treatment for mothers and babies, and the protection of children and adolescents from violence and exploitation. Before, during and after humanitarian emergencies, UNICEF is on the ground, bringing lifesaving help and hope to children and families. Non-political and impartial, we are never neutral when it comes to defending children’s rights and safeguarding their lives and futures. And we never give up.',
    linkOfficial:'https://www.unicef.org/',
    vacancies:["Current Vacancies","https://jobs.unicef.org/cw/en-us/listing/"],
  },
  {
    id:'009',
    title: 'UN Funds and Programmes',
    logo: '/interships/itu.svg',
    company:'International Telecommunication Union (ITU)',
    companyDescription: 'The ITU is the oldest agency of the United Nations. We have been shaping communications, constantly evolving and connecting the world for over 150 years. Our history – and our future – are the history and future of communication technology itself.',
    linkOfficial:'https://jobs.itu.int/',
    believe1:["We believe in the power of technology to improve human lives everywhere","We value technology and technical expertise to help people communicate and prosper. Digital technology drives social and economic development, enabling us to address global challenges such as health and climate. Technology is not for technology’s sake, but for the good of humanity and of the planet."],
    believe2:["We believe in inclusivity","ICTs and the benefits they bring should be available to everyone, everywhere, regardless of nation, economic status, gender, age or ability. We work towards universal access to digital technology, closing the digital divide and opening up opportunity to all. We value collaboration and consensus. We provide a neutral global platform for nations, industries, international organizations, and research institutions to work together on an equal footing and with an equal voice. Building consensus, creating partnerships, and delivering change depend on mutual respect."],
    join:["Join us","Technical expertise, inclusivity, collaboration, and consensus are the hallmarks of our way of working, too. We are respected, trusted professionals in every aspect of our work. We value efficiency, transparency, and accountability. We are proud members of the UN family and fully uphold the UN system values. Above all, we are people with a mission: making technology available to all, for the good of all."],
    vacancies:["Current Vacancies","https://jobs.itu.int/go/Internship/8943055/"],
  },
  {
    id:'010',
    title: 'UN Funds and Programmes',
    logo: '/interships/wto.jpg',
    company:'World Trade Organization (WTO)',
    companyDescription: 'The WTO provides a forum for negotiating agreements aimed at reducing obstacles to international trade and ensuring a level playing field for all, thus contributing to economic growth and development. The WTO also provides a legal and institutional framework for the implementation and monitoring of these agreements, as well as for settling disputes arising from their interpretation and application. The current body of trade agreements comprising the WTO consists of 16 different multilateral agreements (to which all WTO members are parties) and two different plurilateral agreements (to which only some WTO members are parties).',
    linkOfficial:'https://www.wto.org/',
    young: ["Young Professionals Programme","The WTO Young Professionals Programme was launched in 2016 as an opportunity for qualified young professionals from developing and least-developed countries that are members of the WTO to enhance their knowledge regarding WTO and international trade issues. The programme aims to attract professionals from under-represented countries who can consequently improve their chances of being recruited by the WTO and/or other regional and international organizations. The Programme is part of the Secretariat's efforts to increase diversity and broaden the representation of the membership."],
    vacancies:["Current Vacancies","https://www.wto.org/english/thewto_e/vacan_e/ypp_e.htm"],
  },
  {
    id:'011',
    title: 'UN Funds and Programmes',
    logo: '/interships/wipo.PNG',
    company:'World Intellectual Property Organization (WIPO)',
    companyDescription: 'At WIPO we are looking for talented individuals from around the globe to help us develop the global intellectual property system. We employ for a wide range of roles: from software engineers, to designers, lawyers, statisticians and more. Our staff work in multi-disciplinary, multi-cultural teams in a stimulating international setting. We work with governments, IP practitioners, civil society and the private sector to administer global IP services, develop international law and standards, set up collaborative networks, and build capacity in the use of IP for development. The majority of staff positions are based at our Geneva headquarters.',
    linkOfficial:'https://www.wipo.int/portal/en/index.html',
    young: ["Young Experts Program: Growing Future Global IP Leaders","The WIPO “Young Experts Program” (YEP) aims to train the next generation of global IP leaders to help build innovation ecosystems around the world. Through this 2-year program, young and talented individuals will be groomed to not only understand the technical aspects of IP but also apply them in practice, to make an impact in their countries and regions. This is boot camp for your career - and a graduate program for life! Application: Coming soon!"],
    internship:["Internships","https://wipo.taleo.net/careersection/wp_2/jobsearch.ftl?lang=en"],
    vacancies:["Current Vacancies","https://wto.wd3.myworkdayjobs.com/External"],
  },
  {
    id:'012',
    title: 'UN Funds and Programmes',
    logo: '/interships/WorldBankLogo.png',
    company:'World Bank',
    companyDescription: 'The World Bank Group works in every major area of development. We provide a wide array of financial products and technical assistance, and we help countries share and apply innovative knowledge and solutions to the challenges they face. The World Bank Group’s recruitment policy is to hire staff of the highest caliber, on as wide a geographical basis as possible, with preference to nationals of WBG member countries or countries of operations. The World Bank Group offers unique programs that provide learning, staffing, and capacity building opportunities for junior and mid-career professionals to experience first-hand what working at the WBG is like.',
    linkOfficial:'https://www.worldbank.org/',
    internship:["Internships","https://www.worldbank.org/en/about/careers/programs-and-internships"],
  },

];
